## STUDENT INFO:
### 1) Name : Chua Jia Lin, Tan Yi Ya, Evelyn Goh Yuan Qi
### 2) Matric No : A23CS0069, A23CS0187, A23CS0222
### 3) Section : 01

# Phase I: DATA PREPARATION AND CLEANING


This notebook presents the data cleaning and preparation phase of our analysis on CO2 emissions from vehicles. We use two datasets:
- **FuelConsumption.csv**: Provides CO2 emission and fuel consumption data for various car models.
- **Cars2025.csv**: Contains car registration information in Malaysia for the year 2025.

Our objective is to merge these datasets, clean and standardize the data, and perform basic aggregations to uncover early insights.

## i. Data Loading


We begin by importing both datasets using pandas. Data is read directly from Google Sheets using CSV export links. We then check the dimensions of each dataset.

In [ ]:
#import required library
import pandas as pd

In [ ]:
# Load FuelConsumption dataset
print("FuelConsumption.csv:")
fc = pd.read_csv("https://docs.google.com/spreadsheets/d/1y6TL2swXMh_rleRB1t462H4ISz93HWNbWkkMauX9D_0/export?format=csv")
fc.head()

FuelConsumption.csv:

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [ ]:
# Display the rows and columns of FuelConsumption dataset
f_rows = fc.shape[0]
f_columns = fc.shape[1]
print(f"Rows: {f_rows}")
print(f"Columns: {f_columns}")

Rows: 1067
Columns: 13

In [ ]:
# Load cars_2025 dataset
print("cars_2025.csv:")
car = pd.read_csv("https://docs.google.com/spreadsheets/d/1QEz8qpZ5odYL8-cYYfq40NUKeasXeFKH_pmWuLhKfB0/export?format=csv")
car.head()

cars_2025.csv:

     date_reg        type  maker      model  colour         fuel        state
0  2025-01-01     motokar    BYD       Seal   white     electric  Rakan Niaga
1  2025-01-01  window_van    Cam   Placer-X  yellow  greendiesel        Johor
2  2025-01-01         jip  Chery  Jaecoo J7   green       petrol  Rakan Niaga
3  2025-01-01         jip  Chery  Jaecoo J7  silver       petrol  Rakan Niaga
4  2025-01-01         jip  Chery      Tiggo    grey       petrol  Rakan Niaga

In [ ]:
# Display the rows and columns of cars_2025 dataset
c_rows = car.shape[0]
c_columns = car.shape[1]
print(f"Rows: {c_rows}")
print(f"Columns: {c_columns}")

Rows: 263578
Columns: 7

##ii. Data Cleaning, Preparation and Wrangling

In this step, we ensure that both datasets are clean and consistent before merging:

- **Column names** are standardized to lowercase and stripped of whitespace.
- **Categorical string values** are cleaned by converting to lowercase and trimming spaces.
- The `maker` column in the Cars2025 dataset is renamed to `make` to match the FuelConsumption dataset.

After cleaning, we merge both datasets on the `make` and `model` columns using an outer join, ensuring no data is lost during integration.

To handle missing values:
- **Numerical columns** are filled with the **median** of their respective attributes.
- **Categorical columns** are filled with the **mode** (most frequent value).

This wrangling process ensures the merged dataset is clean, consistent, and ready for analysis in the next phase.

In [ ]:
# Convert all the column names to lowercase and strip whitespace
fc.columns = fc.columns.str.strip().str.lower()
car.columns = car.columns.str.strip().str.lower()
print("FuelConsumption:\n",fc.columns)
print("\ncars_2025:\n",car.columns)

# List the Categorical (Object) Data
fc_categorical = fc.select_dtypes(include='object').columns
car_categorical = car.select_dtypes(include='object').columns
print("\nFuelConsumption Categorical:\n",fc_categorical)
print("\ncars_2025 Categorical:\n",car_categorical)

# Convert categorical values to lowercase and strip whitespace
for col in fc_categorical:
    fc[col] = fc[col].str.strip().str.lower()
for col in car_categorical:
    car[col] = car[col].str.strip().str.lower()

FuelConsumption:
 Index(['modelyear', 'make', 'model', 'vehicleclass', 'enginesize', 'cylinders',
       'transmission', 'fueltype', 'fuelconsumption_city',
       'fuelconsumption_hwy', 'fuelconsumption_comb',
       'fuelconsumption_comb_mpg', 'co2emissions'],
      dtype='object')

cars_2025:
 Index(['date_reg', 'type', 'maker', 'model', 'colour', 'fuel', 'state'], dtype='object')

FuelConsumption Categorical:
 Index(['make', 'model', 'vehicleclass', 'transmission', 'fueltype'], dtype='object')

cars_2025 Categorical:
 Index(['date_reg', 'type', 'maker', 'model', 'colour', 'fuel', 'state'], dtype='object')

In [ ]:
# Step 2: Check both dataset
print("FuelConsumption:\n",fc.head())
print("\ncars_2025:\n",car.head())

FuelConsumption:
    modelyear   make       model vehicleclass  enginesize  cylinders  \
0       2014  acura         ilx      compact         2.0          4
1       2014  acura         ilx      compact         2.4          4
2       2014  acura  ilx hybrid      compact         1.5          4
3       2014  acura     mdx 4wd  suv - small         3.5          6
4       2014  acura     rdx awd  suv - small         3.5          6

  transmission fueltype  fuelconsumption_city  fuelconsumption_hwy  \
0          as5        z                   9.9                  6.7
1           m6        z                  11.2                  7.7
2          av7        z                   6.0                  5.8
3          as6        z                  12.7                  9.1
4          as6        z                  12.1                  8.7

   fuelconsumption_comb  fuelconsumption_comb_mpg  co2emissions
0                   8.5                        33           196
1                   9.6                        29           221
2                   5.9                        48           136
3                  11.1                        25           255
4                  10.6                        27           244

cars_2025:
      date_reg        type  maker      model  colour         fuel        state
0  2025-01-01     motokar    byd       seal   white     electric  rakan niaga
1  2025-01-01  window_van    cam   placer-x  yellow  greendiesel        johor
2  2025-01-01         jip  chery  jaecoo j7   green       petrol  rakan niaga
3  2025-01-01         jip  chery  jaecoo j7  silver       petrol  rakan niaga
4  2025-01-01         jip  chery      tiggo    grey       petrol  rakan niaga

In [ ]:
# Step 3: Rename the column name of FuelConsumption to match with cars_2025 dataset
car.rename(columns={'maker': 'make'}, inplace=True)

In [ ]:
# Step 4: Merge both datasets
df = pd.merge(fc, car, on=['make', 'model'], how='outer')
df.head()

,modelyear,make,model,vehicleclass,enginesize,cylinders,transmission,fueltype,fuelconsumption_city,fuelconsumption_hwy,fuelconsumption_comb,fuelconsumption_comb_mpg,co2emissions,date_reg,type,colour,fuel,state
0,2014.0,acura,ilx,compact,2.0,4.0,as5,z,9.9,6.7,8.5,33.0,196.0,NaN,NaN,NaN,NaN,NaN
1,2014.0,acura,ilx,compact,2.4,4.0,m6,z,11.2,7.7,9.6,29.0,221.0,NaN,NaN,NaN,NaN,NaN
2,2014.0,acura,ilx hybrid,compact,1.5,4.0,av7,z,6.0,5.8,5.9,48.0,136.0,NaN,NaN,NaN,NaN,NaN
3,NaN,acura,mdx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-02-03,motokar_pelbagai_utiliti,white,petrol,w.p. kuala lumpur
4,2014.0,acura,mdx 4wd,suv - small,3.5,6.0,as6,z,12.7,9.1,11.1,25.0,255.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Remove duplicated records
df.drop_duplicates(inplace=True)

In [ ]:
# Summarize the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54216 entries, 0 to 278318
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   modelyear                 10188 non-null  float64
 1   make                      54216 non-null  object
 2   model                     54216 non-null  object
 3   vehicleclass              10188 non-null  object
 4   enginesize                10188 non-null  float64
 5   cylinders                 10188 non-null  float64
 6   transmission              10188 non-null  object
 7   fueltype                  10188 non-null  object
 8   fuelconsumption_city      10188 non-null  float64
 9   fuelconsumption_hwy       10188 non-null  float64
 10  fuelconsumption_comb      10188 non-null  float64
 11  fuelconsumption_comb_mpg  10188 non-null  float64
 12  co2emissions              10188 non-null  float64
 13  date_reg                  53240 non-null  object
 14  type                      53240 non-null  object
 15  colour                    53240 non-null  object
 16  fuel                      53240 non-null  object
 17  state                     53240 non-null  object
dtypes: float64(8), object(10)
memory usage: 7.9+ MB

In [ ]:
df.describe()

,modelyear,enginesize,cylinders,fuelconsumption_city,fuelconsumption_hwy,fuelconsumption_comb,fuelconsumption_comb_mpg,co2emissions
count,10188.0,10188.000000,10188.000000,10188.000000,10188.000000,10188.000000,10188.000000,10188.000000
mean,2014.0,2.286170,4.427562,10.020043,7.505389,8.874126,33.197782,203.129172
std,0.0,0.826555,0.999928,2.590368,1.639708,2.161214,6.247351,45.766534
min,2014.0,1.000000,3.000000,4.600000,4.900000,4.700000,11.000000,108.000000
25%,2014.0,1.800000,4.000000,8.100000,6.300000,7.200000,29.000000,166.000000
50%,2014.0,2.000000,4.000000,9.000000,6.800000,8.200000,34.000000,189.000000
75%,2014.0,2.400000,4.000000,11.100000,8.300000,9.800000,39.000000,225.000000
max,2014.0,8.400000,12.000000,30.200000,20.500000,25.800000,60.000000,488.000000

In [ ]:
# Check the missing value
print("Check Missing Value:")
print(df.isnull().sum())

Check Missing Value:
modelyear                   44028
make                            0
model                           0
vehicleclass                44028
enginesize                  44028
cylinders                   44028
transmission                44028
fueltype                    44028
fuelconsumption_city        44028
fuelconsumption_hwy         44028
fuelconsumption_comb        44028
fuelconsumption_comb_mpg    44028
co2emissions                44028
date_reg                      976
type                          976
colour                        976
fuel                          976
state                         976
dtype: int64

In [ ]:
# Split Categorical and Numerical Value
categorical_cols = df.select_dtypes(include='object').columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Handling Missing Numerical Value with Median
for col in numerical_cols:
    if df[col].isnull().sum() > 0:
        df[col].fillna(df[col].median(), inplace=True)

# Handling Missing Categorical Value with Mode
for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        df[col].fillna(df[col].mode()[0], inplace=True)

<ipython-input-39-175096146>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
<ipython-input-39-175096146>:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [ ]:
# Recheck the missing value
print("Check Missing Value:")
print(df.isnull().sum())

Check Missing Value:
modelyear                   0
make                        0
model                       0
vehicleclass                0
enginesize                  0
cylinders                   0
transmission                0
fueltype                    0
fuelconsumption_city        0
fuelconsumption_hwy         0
fuelconsumption_comb        0
fuelconsumption_comb_mpg    0
co2emissions                0
date_reg                    0
type                        0
colour                      0
fuel                        0
state                       0
dtype: int64

In [ ]:
# Recheck the dataset
df.head()

,modelyear,make,model,vehicleclass,enginesize,cylinders,transmission,fueltype,fuelconsumption_city,fuelconsumption_hwy,fuelconsumption_comb,fuelconsumption_comb_mpg,co2emissions,date_reg,type,colour,fuel,state
0,2014.0,acura,ilx,compact,2.0,4.0,as5,z,9.9,6.7,8.5,33.0,196.0,2025-04-30,motokar,white,petrol,rakan niaga
1,2014.0,acura,ilx,compact,2.4,4.0,m6,z,11.2,7.7,9.6,29.0,221.0,2025-04-30,motokar,white,petrol,rakan niaga
2,2014.0,acura,ilx hybrid,compact,1.5,4.0,av7,z,6.0,5.8,5.9,48.0,136.0,2025-04-30,motokar,white,petrol,rakan niaga
3,2014.0,acura,mdx,compact,2.0,4.0,m5,x,9.0,6.8,8.2,34.0,189.0,2025-02-03,motokar_pelbagai_utiliti,white,petrol,w.p. kuala lumpur
4,2014.0,acura,mdx 4wd,suv - small,3.5,6.0,as6,z,12.7,9.1,11.1,25.0,255.0,2025-04-30,motokar,white,petrol,rakan niaga

In [ ]:
# Display the rows and columns of combined dataset
d_rows = df.shape[0]
d_columns = df.shape[1]
print(f"Rows: {d_rows}")
print(f"Columns: {d_columns}")

Rows: 54216
Columns: 18

##iii. Data Aggregation and Group Operations

We conduct grouping operations to analyze:
- **Emissions by Car Maker**: Average CO2 emissions and fuel consumption, number of models.
- **Vehicle Class**: How vehicle types differ in average emissions.
- **Fuel Type**: How different fuels impact CO2 output.
- **State**: Regional comparison of emissions and consumption.

These aggregations reveal patterns relevant for identifying high-emission segments.

In [ ]:
# Group by Car Manufacturer to shows which manufacturers produce more polluting vehicles on average.
grouped_make = df.groupby('make').agg({
    'fuelconsumption_comb': 'mean',
    'co2emissions': 'mean',
    'model': 'count'  # number of models registered
}).rename(columns={'model': 'car_count'}).reset_index()

grouped_make.sort_values(by='co2emissions', ascending=False).head()

           make  fuelconsumption_comb  co2emissions  car_count
77          srt             16.900000    389.000000          2
73  rolls-royce             16.571429    381.000000          7
30          gmc             16.755102    328.244898         49
70          ram             13.569231    291.230769         13
11     cadillac             12.896875    287.343750         32

In [ ]:
# Group by Vehicle Class to analyze how different vehicle types contribute to emissions
grouped_class = df.groupby('vehicleclass').agg({
    'fuelconsumption_city': 'mean',
    'fuelconsumption_hwy': 'mean',
    'co2emissions': 'mean'
}).reset_index()
grouped_class.sort_values(by='co2emissions', ascending=False).head()

,vehicleclass,fuelconsumption_city,fuelconsumption_hwy,co2emissions
15,van - passenger,23.228000,16.760000,401.000000
14,van - cargo,20.881818,16.059091,361.500000
6,pickup truck - standard,17.009677,12.435484,309.096774
12,suv - standard,15.027929,10.752006,296.617978
5,pickup truck - small,13.750000,10.633333,284.250000

In [ ]:
# Group by Fuel Type to compares how fuel types affect emissions and fuel consumption.
grouped_fuel = df.groupby('fuel').agg({
    'co2emissions': ['mean', 'max'],
    'fuelconsumption_comb': 'mean'
}).reset_index()
grouped_fuel.sort_values(by=[('co2emissions', 'mean'), ('co2emissions', 'max'), ('fuelconsumption_comb', 'mean')],ascending=[False, False, False]).head()

            fuel co2emissions        fuelconsumption_comb
                         mean    max                 mean
5         petrol   192.313400  488.0             8.359295
4  hybrid_petrol   191.906933  313.0             8.329916
0         diesel   189.656457  262.0             8.228688
1       electric   189.000000  189.0             8.200000
2    greendiesel   189.000000  189.0             8.200000

In [ ]:
#Group by State to reveals regional differences in vehicle emissions, possibly related to policy or consumer behavior
grouped_state = df.groupby('state').agg({
    'co2emissions': 'mean',
    'fuelconsumption_comb': 'mean'
}).reset_index()
grouped_state.sort_values(by='co2emissions', ascending=False).head()

                state  co2emissions  fuelconsumption_comb
14  w.p. kuala lumpur    192.510573              8.355027
9         rakan niaga    192.454811              8.369308
0               johor    190.891640              8.284566
12           selangor    190.775728              8.279648
8        pulau pinang    190.411084              8.263459



In this phase, we successfully cleaned and merged real-world data on car emissions and registrations. By handling missing data and preparing it for analysis, we created a reliable dataset for further analytics. Initial group-level insights reveal which vehicle classes and fuel types are most emission-intensive. This sets the foundation for deeper exploration in Phase II.